import type { ThemeDefinition } from './types'

export const desertYellow = {
  id: 'desertYellow',
  name: '沙漠黄',
  ui: {
    page: '#F5F1E8',
    surface: '#FFFDF8',
    primary: '#D98B16',
    text: '#29333A',
    muted: '#73808A',
    border: '#EEE7DA',
    overlay: 'rgba(41, 51, 58, 0.32)',
    dangerSurface: '#FFF0EB',
    dangerText: '#8A3B2F',
    onPrimary: '#FFFFFF',
  },
  appearance: {
    pickerRadius: '24rpx',
    pickerBorder: '0 solid transparent',
    pickerShadow: '0 8rpx 22rpx rgba(41, 51, 58, 0.06)',
    settingsRadius: '24rpx',
    settingsBorder: '0 solid transparent',
    mapRadius: '28rpx',
    mapBorder: '0 solid transparent',
    mapShadow: '0 12rpx 30rpx rgba(41, 51, 58, 0.08)',
    actionRadius: '14rpx',
    primaryActionBorder: '0 solid transparent',
    secondaryActionBorder: '2rpx solid #D98B16',
    secondaryActionText: '#D98B16',
    errorBorder: '0 solid transparent',
    panelRadius: '32rpx 32rpx 0 0',
    panelBorder: '0 solid transparent',
    dividerBorder: '1rpx solid #EEE7DA',
    closeRadius: '999rpx',
    closeBorder: '0 solid transparent',
    closeBackground: '#FFF8EA',
    closeText: '#D98B16',
    closeLineHeight: '56rpx',
    stepRadius: '12rpx',
    stepBorder: '1rpx solid #EEE7DA',
    stepBackground: '#FFF8EA',
    summaryRadius: '20rpx',
    summaryBorder: '0 solid transparent',
    summaryText: '#52616B',
  },
  scene: {
    canvas: '#F7F4EC',
    numberToken: '#FFF7DD',
    numberText: '#24313A',
    highProbabilityNumber: '#C83A2F',
    title: '#29333A',
    mutedText: '#73808A',
    summaryText: '#52616B',
    algorithmText: '#8A959C',
  },
  platform: {
    navigationBarBackground: '#F5F1E8',
    navigationBarTextStyle: 'black',
  },
} as const satisfies ThemeDefinition
