import type { ThemeDefinition } from './types'

export const stoneBlue = {
  id: 'stoneBlue',
  name: '石板蓝',
  ui: {
    page: '#DDE5EA',
    surface: '#EEF2F3',
    primary: '#647D8C',
    text: '#3E5664',
    muted: '#71838D',
    border: '#B9C8CF',
    overlay: 'rgba(62, 86, 100, 0.38)',
    dangerSurface: '#E8DEDD',
    dangerText: '#805D5A',
    onPrimary: '#FFFFFF',
  },
  appearance: {
    pickerRadius: '18rpx',
    pickerBorder: '2rpx solid #B9C8CF',
    pickerShadow: 'none',
    settingsRadius: '18rpx',
    settingsBorder: '2rpx solid #3E5664',
    mapRadius: '22rpx',
    mapBorder: '2rpx solid #B9C8CF',
    mapShadow: 'none',
    actionRadius: '16rpx',
    primaryActionBorder: '2rpx solid #647D8C',
    secondaryActionBorder: '2rpx solid #647D8C',
    secondaryActionText: '#3E5664',
    errorBorder: '2rpx solid #B9C8CF',
    panelRadius: '28rpx 28rpx 0 0',
    panelBorder: '2rpx solid #B9C8CF',
    dividerBorder: '2rpx solid #B9C8CF',
    closeRadius: '14rpx',
    closeBorder: '2rpx solid #B9C8CF',
    closeBackground: '#DDE5EA',
    closeText: '#3E5664',
    closeLineHeight: '52rpx',
    stepRadius: '12rpx',
    stepBorder: '2rpx solid #B9C8CF',
    stepBackground: '#DDE5EA',
    summaryRadius: '18rpx',
    summaryBorder: '2rpx solid #B9C8CF',
    summaryText: '#3E5664',
  },
  scene: {
    canvas: '#EEF2F3',
    numberToken: '#E9EDF0',
    numberText: '#3E5664',
    highProbabilityNumber: '#79534F',
    title: '#3E5664',
    mutedText: '#71838D',
    summaryText: '#526A76',
    algorithmText: '#71838D',
  },
  platform: {
    navigationBarBackground: '#DDE5EA',
    navigationBarTextStyle: 'black',
  },
} as const satisfies ThemeDefinition
